### ISSUE TITLE
Add a REST API for spawning jobs

### ISSUE THREAD

**Issue by pixelspark** [ErikTromp/Tuktu#1]
Hi Erik, Tuktu looks nice, I also like the modeller. It would be great if I could try to integrate Tuktu as a back-end to [Warp, a query-by-example tool](https://pixelspark.nl/2015/warp-a-query-by-example-analysis-tool-for-big-data) I am currently working on. 

Is there an API using which I could start arbitrary JSON jobs? (This obviously needs some sort of security or sandboxing, because such an API would allow users of it to read any CSV file accessible to Tuktu...). Would be even better if I could also upload files to a working directory for a job, then start a job on those files. This would also be a great way to deploy Tuktu 'as a service' (interesting business model for you perhaps).

The following is a suggestion for a REST API:

```
- GET /api/v1/job: Retrieves a list of jobs
- POST /api/v1/job (name=TestJob): creates a temporary directory 'TestJob' somewhere
- GET /api/v1/job/TestJob: retrieves information about a job (e.g. name, date created, running status, etc.)
- GET /api/v1/job/TestJob/configuration: retrieves the JSON configuration of a job
- POST /api/v1/job/TestJob/configuration (json={...}): sets the JSON configuration for job 'TestJob' to the JSON sent
- POST /api/v1/job/TestJob/start: starts job TestJob
- POST /api/v1/job/TestJob/stop: stops job TestJob
- POST /api/v1/job/TestJob/files/test.csv: Uploads file 'test.csv' to the working directory of the job
- DELETE /api/v1/job/TestJob/files/test.csv: Removes file 'test.csv' from the working dir
- GET /api/v1/job/TestJob/files: Retrieves a list of all working directory files for a job
- GET /api/v1/job/TestJob/files/test.csv: Retrieve file 'test.csv' from the working directory
```

Best,
Tommy.

**Comment by ErikTromp** [comment]
Agreed - this would be nice. I will put this on the to-do list for after my holidays. I do want to have some proper storage in place (HDFS for example) before this one, perhaps also getting some user authentication in.

For now though, you can already spawn (asynchronous) jobs using a GET to tuktu-url.com/dispatch/:id where :id is the name of the config stored in Tuktu's repository. Alternatively you can POST a complete config to tuktu-url.com/config, having as additional parameter in the JSON a top-level field "id" that is the name of the config (doesn't have to exist on Tuktu, but has to be unique).

**Comment by pixelspark** [comment]
That would be great, @ErikTromp. 

Please consider also leaving the current storage options in; deploying HDFS is still a lot more difficult than unzipping Tuktu, dragging in some CSVs and run it. This makes Tuktu friendly and low-entry. If you don't want to support file uploads through the Tuktu API then maybe you should consider accepting URLs to input files instead (if that's not already possible right now). You could nicely integrate with HDFS by using special 'hdfs://' URLs for data stored in HDFS.

**Comment by ErikTromp** [comment]
True, that is what I had planned too. Ideally, I would want to make a Tuktu-specific way of doing this (but HDFS support will be (optionally) required at some point anyway).

**Comment by ErikTromp** [comment]
I am going to start working on this one iteratively. Note that I need some other stuff in place before I can do the actual endpoints though (file reader/writer abstractions, user auth (will use HTTP basic auth for now), directory support in configs and repo and maybe some more).

I intend on making available a file:// (already there), an hdfs:// (working on it) and a tuktu:// (not there yet) scheme. The latter will allow to have files submitted on a node and jobs ran on it regardless of their location (not true for the first case).

**Comment by ErikTromp** [comment]
Finally made a first, very basic, version of this, in module restapi.
File handling isn't there yet, because for that I need an API around the TDFS system, which is a separate module.
