### ISSUE TITLE
TDFS loses track of all part files when Tuktu is rebooted

### ISSUE THREAD

**Issue by ErikTromp** [ErikTromp/Tuktu#15]
If a cluster's node (Tuktu) is restarted, TDFS only sees the files present on the local node and seems to 'forget' all the part files on the other nodes.

**Comment by mirekvink** [comment]
I've come across the following:
- up and downloading via the filebrowser is always non-binary. This might be a design choice but should be clearly mentioned as I've tried initially with binary files (e.g. zip files).
- Having created a 128mb text file and uploaded it on stand alone Tuktu, uploading is fast. Downloading has a lot of resources overhead, I see quite a bit of CPU load and it's fairly slow actually (~200kb/s)
- The same 128mb text file gets distributed over 2 nodes, however downloading seems to frequently just stop downloading (no errors and connection remains open).

The issue about forgetting part files doesn't seem to occur on my side. It has the correct number of part files mentioned in my filebrowser.

**Comment by ErikTromp** [comment]
While these other issues are true (although I reach 1.5mb/s), the actual part files works.
