### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by ziming** [ErikTromp/Tuktu#2]
Just browsing around your project Erik. :)

Wonder if you heard of these awesome-X lists

https://github.com/onurakpolat/awesome-bigdata

I think it may be good to suggest your project to them 1 day when you felt Tuktu is ready to get more exposure.

Good luck!

**Comment by ErikTromp** [comment]
Definitely a  good pointer, thanks

**Comment by ErikTromp** [comment]
Created a pull request
